In [1]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(314159)
num_imgs = 5 
dim = 3
imgs  = np.ceil( np.random.rand(num_imgs, dim**2) * 10) 
imgs = [ [num]*9 for num in range(5)]
print('imgs\n', imgs)

assigns = np.array([1,0,1,1,0])
print('assigns: ', assigns)

#centers = np.array(([1,2,3,4,5,6,7,8,9], [10,11,12,13,14,15,16,17,18]))
centers = np.array(([1,1,1,1,1,1,1,1,1], [0,0,0,0,0,0,0,0,0]))
print('centers\n',centers)

#print(aCluster)

clusters = []
for k in range(2):
    #aCluster = np.array(np.zeros(dim**2))
    #print('~~~~~', k,'~~~~~')
    #xIndices = np.where(assigns==k)
    #print('xindices', xIndices)
    #aCluster = np.stack([imgs[xidx] for xidx in xIndices
    #print('aCluster, ', aCluster)
    #clusters.vstack(clusters,aCluster)
    cluster = np.array([imgs[i] for i in range(len(imgs)) if assigns[i] == k])
    print('k=', k, 'cluster\n', cluster)
    clusters.append(np.mean(cluster, axis=0))
    
print('clsters\n', np.array(clusters))
    



imgs
 [[0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2, 2], [3, 3, 3, 3, 3, 3, 3, 3, 3], [4, 4, 4, 4, 4, 4, 4, 4, 4]]
assigns:  [1 0 1 1 0]
centers
 [[1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]]
k= 0 cluster
 [[1 1 1 1 1 1 1 1 1]
 [4 4 4 4 4 4 4 4 4]]
k= 1 cluster
 [[0 0 0 0 0 0 0 0 0]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]]
clsters
 [[2.5        2.5        2.5        2.5        2.5        2.5
  2.5        2.5        2.5       ]
 [1.66666667 1.66666667 1.66666667 1.66666667 1.66666667 1.66666667
  1.66666667 1.66666667 1.66666667]]


In [3]:
a = np.array([1,3,1,2,4])
np.where(a==1)
np.array([[num]*9 for num in range(5)]).reshape(5,3,3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]])

In [14]:
const = 6000*28**2

objs = np.array([2.970801283825729,
2.1593113092850316,
2.053740173112835,
2.028430170271818,
2.020434618936546,
2.014945309442909,
2.009952545073193,
2.0058719436530668,
2.0020712697939245,
1.9991800240967197,
1.9956847391084258,
1.9925334013885792,
1.9902212840037334,
1.9887275711185066,
1.9879460378803453,
1.9874940357430189,
1.9872573609899558,
1.9871233588398067,
1.9869498237054917,
1.9868501233662605,
1.9868079718580767,
1.986795990298887,
1.9867798515068982,
1.986773534909377,
1.986773534909377])



xs = np.arange(objs.shape[0])
plt.plot(xs, objs*const, marker='x')
plt.ylim(ymin=0)
plt.title('MNIST Kmeans Objective, K=10, converged at iter=24\n')
plt.xlabel('Iterations')
plt.ylabel('Objective (l2 norm)')

ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
PySide or PySide2 package to be installed, but it was not found.

In [4]:
plt.show()